name: Workflow for Codecov example-javascript
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Initialise Node
        run: npm init -y
      - name: Install Firebase
        run: npm install firebase 
      - name: npm run start
        run: npm run start
